services:
  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data/user_history:/app/data/user_history
    env_file:
      - .env

  streamlit:
    build: .
    command: streamlit run app/dashboard.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data/user_history:/app/data/user_history
    env_file:
      - .env
    depends_on:
      - api
